import { saveAs } from 'file-saver'
import Ticketing from "../images/Ticketing.png"
import React, { useState } from "react";
import { View, Text, Dimensions, TouchableOpacity, LogBox } from "react-native";
import Theme from "../assets/Theme/Theme";
import TickTextField from "../common/TickTextField";
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';
import TickButton from "../common/TickButton";
import { useNavigation } from "@react-navigation/native";
import { Image } from 'react-native'
const SCREEN_HEIGHT = Dimensions.get('window').height;

const Whatis2 = () => {
    
    const useNavigate = useNavigation();

    const navigationWhatis3 = () => {
        useNavigate.navigate('Whatis3');
    }
    return (
        <KeyboardAwareScrollView style={[{ height: SCREEN_HEIGHT }]}>
            <View style={[{ height: SCREEN_HEIGHT }]}>
                <View style={[Theme.container, Theme.w100, Theme.h100, Theme.bgMainj]}>
                    <View style={[Theme.w98, Theme.h7, Theme.justAlign]}>
                        <Text style={[Theme.fWhite, Theme.f20]}>What is solar panel system?? </Text>
                    </View>
                    
                    <View style={[Theme.w98, Theme.h90, Theme.border1_5, Theme.bgMainj, Theme.justAlign]}>
                       
                        <View style={[Theme.dFlexCol]}>
                            {/* schedule images ---------------------------------------------------------------------------------------------------- */}
                            {<Image source={require('../images/Blog2.png')} 
                            style = {{ width: 250, height: 150 }} />}
                        </View>

                        <Text style={[Theme.fGray, Theme.f20]}> How Do Solar Panels Work? </Text>
                        
                        <Text style={[Theme.fBlack, Theme.f20]}> Your</Text>

                        <Text style={[Theme.fWhite, Theme.f15]}> 
                        Solar panels collect clean renewable energy in the form of sunlight and convert that light into electricity which can then be used to provide power for electrical loads. Solar panels are comprised of several individual solar cells which are themselves composed of layers of silicon, phosphorous (which provides the negative charge), and boron (which provides the positive charge). Solar panels absorb the photons and in doing so initiate an electric current. The resulting energy generated from photons striking the surface of the solar panel allows electrons to be knocked out of their atomic orbits and released into the electric field generated by the solar cells which then pull these free electrons into a directional current. This entire process is known as the Photovoltaic Effect. An average home has more than enough roof area for the necessary number of solar panels to produce enough solar electricrity to supply all of its power needs excess electricity generated goes onto the main power grid, paying off in electricity use at night.
                        </Text>

                        <Text style={[Theme.fBlack, Theme.f20]}> Your</Text>

                        <View style={[Theme.w80, Theme.h7]}>
                            <TickButton
                                onPress={() => navigationWhatis3()}
                                ButtonName={"Next"}
                            />
                        </View>
                    </View>
                </View>
            </View>
        </KeyboardAwareScrollView>


    )
}

export default Whatis2;


